---
abstract: 'A Module::Build class for building XS modules'
author:
  - ':'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.4005
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-XSUtil
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Module::Build::XSUtil:
    file: lib/Module/Build/XSUtil.pm
    version: 0.02
requires:
  Devel::CheckCompiler: 0.02
  Devel::PPPort: 3.19
  Exporter: 0
  ExtUtils::CBuilder: 0
  File::Basename: 0
  File::Path: 0
  XSLoader: 0.02
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/hideo55/Module-Build-XSUtil/issues
  homepage: https://github.com/hideo55/Module-Build-XSUtil
  repository: git://github.com/hideo55/Module-Build-XSUtil.git
version: 0.02
x_contributors:
  - 'hideo55 <hide.o.j55@gmail.com>'
