---
abstract: 'Perl extension for blah blah blah'
author:
  - 'A. U. Thor, author\@example.com'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.42
  Module::Build::XSUtil: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Foo
provides:
  Foo:
    file: lib/Foo.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
